### ISSUE TITLE
Update variables from IDS with adjustments to Jetto variables

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#286]
Find  a way to update jetto variables from IDS with adjustments (when not implemented in Jetto).
This might be in the scope of Jetto, then we would only have to update IDS variables

- [ ] Coupling IDS and Jetto variables might do the trick here, although if there is a complex mathematical relationship this would probably not work
- [ ] Find a way to have "post functions" which execute on every case in the generated ensemble and can do arbitrary work on the individual run points

More ideas are welcome :)
Code snippet with how its currently done:
https://github.com/CarbonCollective/fusion-dUQtools/blob/9de484fd6fb26226325d93ac812877de9c2cef00/scripts/prepare_im_runs.py#L341-L355

**Comment by fcasson** [comment]
Again to understand what you want to do here I would need an example use case...

**Comment by stefsmeets** [comment]
I think we pretty much covered this with #494 and #502
