### ISSUE TITLE
Error conditions if variables do not exist in IDS when plotting via API

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#314]
Currently it errors out with mismatching dimensions, can we do better?

**Comment by stefsmeets** [comment]
I discussed this also with @aaronkho yesterday, and we agreed that it _may_ be useful to default to 0 when the variables do not exist.

One of the use-cases we thought about is if you are loading a bunch of data sets, but one or two are missing a variable. In that case, it may be useful to fill missing data with 0 (or nan). To do partial plots.

I don't think this should be the default though. 

We could follow the pandas/xarray convention to fill nan on missing data, and then use the `.fillna` method to fill the data with 0s (https://docs.xarray.dev/en/stable/generated/xarray.DataArray.fillna.html).

**Comment by stefsmeets** [comment]
Something like this:

```python
from duqtools.api import Variable, ImasHandle

NonExistantVar = Variable(
    ids='core-profiles', 
    path='profiles_1d/*/does/not/exist', 
    dims=('time', 'x'), 
    name='does-not-exist')

variables = ('rho_tor_norm', 'time', 't_i_ave', NonExistantVar)

ImasHandle.get(variable=variables) # raises KeyError
# or
ImasHandle.get_variables(variables=variables, fillna=True)  # returns with 0s or NaNs for 'does-not-exist'
```

**Comment by stefsmeets** [comment]
You can now do:

```python
handle.get_variables(variables=variables, empty_var_ok=True)
# or
data_map = handle.get('core_profiles')
data_map.to_xarray(variables, empty_var_ok=True)
```

This will skip loadingn the data. Merging the data afterwards should be done by the user or through [`xr.concat`](https://docs.xarray.dev/en/stable/generated/xarray.concat.html). I'm not convinced this is a trivial problem to solve for the general case.

I played around a bit with `xr.concat`, but could not find a solution that I was satisfied with yet.
