### ISSUE TITLE
duqtools init outputs $USER, which is not valid

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#397]
We should replace it with the actual username of the user

**Comment by v1kko** [comment]
or, alternatively, patch pydantic such that it knows to substitute the value with the environment variable

**Comment by stefsmeets** [comment]
To keep it simple, `init` just copies the config. 

I tried to process the config with pydantic, but the issue is that it outputs a path that probably does not exist for the user.

**Comment by stefsmeets** [comment]
This is solved by removing the workspace entirely in #419
