### ISSUE TITLE
Which python versions to support

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#398]
The gateway seems to be using python3.10 for the jintrac modules. Does this mean support for python3.7 can be dropped?

**Comment by v1kko** [comment]
In preperation I created #402

**Comment by stefsmeets** [comment]
Worth noting that some libraries we depend on like scipy and numpy already dropped support for Python 3.7.

3.11 is very new and will need some time for libraries to catch up.

**Comment by stefsmeets** [comment]
Docker image is at 3.9, seems like a good target if we drop support for python 3.7 in a couple of months.
