### ISSUE TITLE
Lock development versions in requirements file or equivalent

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#406]
To help with development and and creating a consistent environment for the CI runners, we should lock the versions of our dependencies in a requirements file, i.e. `requirements-dev.txt` or some other lockfile.

Users wishing to reproduce our environment can then do so as well, which will help with dependency management in the future.

I think the requirements-dev.txt should manage the versions of our direct dependencies only. Any indirect dependencies *can* be stored in a lockfile, but it is probably not necessary at this stage.

Follow-up from discussion in #402

**Comment by stefsmeets** [comment]
How about this, @v1kko?

**Comment by v1kko** [comment]
Agree, I created #405 as well, I just have the concern that if we pin dependencies in development, we will forget to update them periodically

**Comment by v1kko** [comment]
- [ ] Pinning of dependencies with pypi releases, this would ensure that `pip install duqtools` keeps working even if one of the dependencies has breaking changes in new versions:
    - [ ] create a `requirements_release.txt` or equivalent
- [ ] Pin the versions in the development version, not sure about this
   - [ ] create a `requirements_dev.txt` or equivalent, probably makes a `requirements_release.txt` obsolete

**Comment by stefsmeets** [comment]
Agree, though this can be solved via an action that runs monthly and checks for updates or installs against the latest version of all packages and checks for compatibility.

There are also services like https://github.com/dependabot, which may be worth trying

**Comment by v1kko** [comment]
Yes, the more you pin, the more overhead it creates, just leaving it be while we are actively developing might actually be the best thing to do

**Comment by v1kko** [comment]
Lets create this `requirements.txt` whenever we create a new release, we wouldn't use it, but it would give a nice indication to users what the packages where at the time of release of that version

**Comment by stefsmeets** [comment]
If we end up revisiting this in the future, I would be curious to see if [pip-tools](https://github.com/jazzband/pip-tools) could be useful.
