### ISSUE TITLE
Documentation: make a presentations section

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#410]
We should add all the slides/presentations/papers stemming from duqtools to the documentation. Because these can have quite a large filesize we should link them from another repostiory

- [x] create a presentations/disseminations section
- [x] create a repository to store dissemination material
- [x] link this to the RSD (mentions) somehow

**Comment by v1kko** [comment]
@stefsmeets  I am thinking about using zenodo as a repository to link materials from, it's pretty much guaranteed to keep existing (with doi!) there as long as CERN exists. What do you think?

**Comment by stefsmeets** [comment]
It's a nice idea! Although don't you find updating to Zenodo a bit of a hassle?

Might be easier to just dump everything in a GH repo.

**Comment by v1kko** [comment]
Zenodo has immutable (data) state, so updating always means creating a new version or new upload.

But I agree, I will create a github repository for now, it can always later be uploaded to zenodo

**Comment by stefsmeets** [comment]
Either way works for me :-)
