### ISSUE TITLE
Merge command, make an option to merge as much as possible

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#416]
- take special care for options which might have a random order (profiles_1d.ions)

- what do we do with unmergeable data
   - we can check for the existence of error bars, before merging?

- can we check the quality of the std , print a warning if it is not a standard deviation?

**Comment by stefsmeets** [comment]
More practical questions arise:
- How do we load every single data variable in the dataset?
- How do we get it into an xarray dataset?
    - (Or do we do this on the IDSMapping directly?)
- How do we deal with integer values, i.e. indices
- Somehow the data dictionary has labels for the data {constant} / {variable}, can this be retrieved somehow?
