### ISSUE TITLE
Upload to Zenodo

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#424]
Just a reminder that we should set up the link with Zenodo to publish there whenever we create a release on github.

**Comment by v1kko** [comment]
https://github.com/duqtools/duqtools/settings/hooks I think the hook is already set up?

**Comment by stefsmeets** [comment]
Alright, nicely done! I think we should make sure to add it somewhere on the docs / readme. 

Also don't forget to add yourself as an author on the latest version 😅

**Comment by v1kko** [comment]
I think I am an author, but for the description it just takes the creator of the release as author, and I think there cannot be two release authors?

**Comment by stefsmeets** [comment]
I usually add everyone who contributed to every release on Zenodo.

Let's say someone uses `duqtools` and cites the latest release in their paper:

`Stef Smeets. (2022). duqtools/duqtools: 1.1.1 (1.1.1). Zenodo. https://doi.org/10.5281/zenodo.7326505`

It completely ignores your and @aaronkho contributions to the code :-) We need to set up the [zenodo config](https://developers.zenodo.org/#github) to get this right automatically, otherwise it takes some manual work every release.

**Comment by stefsmeets** [comment]
I created a new issue to set this up.
