### ISSUE TITLE
Dashboard revamp merge and plotting section

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#439]
- [x] plot revise selection of variables
- [x] merge revise selection of variables
- [x] merge: `--all` option can be introduced, to try and merge all known variables

**Comment by stefsmeets** [comment]
Same goes for the plotting. We can just list all variables, and I think we do not need to allow the user to select the `grid` / `time` variable anymore if they are embedded in the variable itself.

**Comment by stefsmeets** [comment]
Closed by #445
