### ISSUE TITLE
Add in JAMS cli java tooling to duqtools create to validate configs

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#453]
Essentially the JAMS CLI applies all the internal logic and can take a `jetto.jset` and turn it into `jetto.in`. This means we could just write `jetto.jset` and let JAMS handle the rest.

If this works well, we could remove all the `jetto.jset`<->`jetto.in` code from `duqtools`.

**Comment by v1kko** [comment]
This could be placed at multiple levels (`duqtools`, `jetto-tools`,`jintrac`).
- Probably the right level would be `jetto-tools`

**Comment by stefsmeets** [comment]
Closing this as out of scope.
