### ISSUE TITLE
Location of IDS definitions is hardcoded

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#464]
Not sure if this will cause issues, but we should fix it for the docker image.

https://github.com/duqtools/duqtools/blob/d9d135412b75074ae73e96e2b74a3a1aa18f17a2/src/duqtools/ids/_imas.py#L14

**Comment by v1kko** [comment]
It indeed causes issues, I find that it might be better defined as:
```python
import os

IMAS_PREFIX = os.getenv('IMAS_PREFIX','')
PATH_IDSDEF = f'{IMAS_PREFIX}/include/IDSDef.xm
```
