### ISSUE TITLE
While creating IMAS database entry, there is no error when creation fails

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#467]
- I have checkt the python AL source code, at least `create_env` always returns success, even if there is no success, so we will have to find another way to check this
- Maybe we can leverage the entry-existence check in `duqtools create` somehow

**Comment by stefsmeets** [comment]
What case did you encounter where it fails?

**Comment by v1kko** [comment]
within the container, while doing a `duqtools create`. Since there is no user defined `imasdb` no entry per run was generated, but no error was generated either

**Comment by v1kko** [comment]
Closing this as the create step now *does* complain when it cannot update imas-values. maybe erroring out is not necessary
