### ISSUE TITLE
Make duqtools compatible with local imasdb's (Jintrac v220922)

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#484]
I'm getting a bunch of failed jetto runs, because duqtools create no longer writes the run number to the `jintrac_imas_config.cfg` file. Defaults to the next number in sequence (1, 2, 3 etc). This causes my runs to fail.

- I checked that `jetto.jset` has the correct run numbers.
- Also seems to be happening with older runs that ran successfully previously.

**Comment by stefsmeets** [comment]
I've tracked it down to `createworkflowcfg` in `v220922`: `/gss_efgw_work/work/g2fjc/jintrac/v220922/sh/createworkflowcfg`, which defines `$RUN_IN` / `$RUN_OUT` as 1 and 2.

In the old version (`v210921`: `/gss_efgw_work/work/g2fjc/jintrac/v210921/sh/createworkflowcfg`), $RUN_IN and `$RUN_OUT` were defined as `SetUpPanel.idsIMASDBRunid` and `obProcessingPanel.idsRunid`.

**Comment by stefsmeets** [comment]
Ok this seems to be related to the change to have the data in the local directory. Getting this to work should be our top priority.

From @aaronkho:

> They have changed the way that JINTRAC handles IDS in and out. Now, they only store the output in the local imasdb folder with input = 1 and output = 2. It no longer writes the output back out to the user's public/imasdb.
So duqtools now needs an additional step to copy the set of output IDSs back to the user's public imasdb, with the run numbers specified in the duqtools.yaml

**Comment by v1kko** [comment]
I would forgo the copying back to the public imasdb (if possible). I think they want to replace that with some "publish" command

**Comment by stefsmeets** [comment]
Seems like we need to create this filetree inside the jetto run directory:

```
.
├── imasdb
│   └── jet
│       └── 3
│           ├── 0
│           │   ├── ids_123450001.characteristics
│           │   ├── ids_123450001.datafile
│           │   ├── ids_123450001.tree
│           │   ├── ids_123450002.characteristics
│           │   ├── ids_123450002.datafile
│           │   └── ids_123450002.tree
│           ├── 1
│           ├── 2
│           ├── 3
│           ├── 4
│           ├── 5
│           ├── 6
│           ├── 7
│           ├── 8
│           └── 9
│ ...
```

**Comment by stefsmeets** [comment]
My understanding is that the `user` is overloaded with the full path to the data. From looking at the code it seems that the username must start with `/` for it to be recognized as a path.

**Comment by v1kko** [comment]
> My understanding is that the `user` is overloaded with the full path to the data. From looking at the code it seems that the username must start with `/` for it to be recognized as a path.

Amazing work 😎!

**Comment by v1kko** [comment]
Does this mean that it always has to be an absolute path? what happens when the folder "moves" (is put inside a container at a different path)

**Comment by stefsmeets** [comment]
I think so, if I put a local path to the directory it errors out:

```python
n [41]: p = Path(user, 'aug', '3', '0', 'ids_369821000.datafile')

In [42]: p
Out[42]: PosixPath('imasdb/aug/3/0/ids_369821000.datafile')

In [43]: p.exists()
Out[43]: True

In [44]: n = idss.open_env(user, 'aug', str(imas_version.major))
--- Logging error ---
<...>
/imas_3_37_0_ual_4_11_0/ids.py", line 391, in open_env
    status = ull.ual_open_pulse(idx, OPEN_PULSE, opt)
Message: b"ual_open_pulse: [UALBackendException = Can't find or access imasdb user's data]"
Arguments: ()
```

**Comment by stefsmeets** [comment]
I think this part in the config pretty much needs to go:

```
  data:
    imasdb: aug
    run_in_start_at: 2000
    run_out_start_at: 2025
```

`data_in` will simply be `aug/shot/1` and `data_out` will be `aug/shot/2`. The user will be set to `<location of the run-directory>/imasdb`

**Comment by stefsmeets** [comment]
This line should be changed and become a method on `system`: https://github.com/duqtools/duqtools/blob/3dd2f0c838adde867bf1f4f35de8057808148f9d/src/duqtools/create.py#L186

It should take care of copying the imas data to the right location.

**Comment by fcasson** [comment]
FAQ#1 Why do JAMS/JINTRAC based workflows now move IDS input and output data into the run directory and not use my ~/public dir anymore?
 
A: The motivations for this change are several:

- No need to track IMAS runid numbers and manage a limited address space (see https://jira.iter.org/browse/IMAS-1872, https://jira.iter.org/browse/IMAS-2698). For data you want to keep long term, it should now go into SimDB catalog which tracks both IDS input and output and all the other files JINTRAC needs in a single location.
- For cloud submission, it is better to encapsulate all input and output data into one directory, so the run can be packed up and sent off in a single tarball
- The long term evolution of IMAS with AL 5 will take us away from the concept of the fixed location for imasdb, which is somewhat broken for the reasons above.

**Comment by fcasson** [comment]
Sorry if this change caused your problems - in the long term I believe it will be a lot more felxible

**Comment by stefsmeets** [comment]
@fcasson Thanks for the explanation. I understand the motivation and fully agree with the change. For our code however, I'm not super keen on supporting multiple paradigms. I think it will take too much of our time support and test for both. I'd rather duqtools works well with the current paradigm.

For the moment, I was thinking we can add a few new systems to the duqtools config:

- `jetto_v210921` -> old 'paradigm'
- `jetto_v220922` -> local imasdb
- `jetto` -> alias for `jetto_v220922`

In this way we can keep the old way around for a while. It just works, we don't really have to add anything. What do you think @v1kko?

**Comment by v1kko** [comment]
That would be a great way to use our `System` system, I do wonder if we would ever use `jetto_v210921` in the future, but since creating an extra system is easy this does not matter.

**Comment by fcasson** [comment]
To clarify, JETTO is not going back, and we don't really need the old method anymore, but if you want to attract non-JETTO IMAS use cases for duqtools, most of those are probably still using the `~/public/imasdb` folder paradigm for awhile yet.

**Comment by stefsmeets** [comment]
> To clarify, JETTO is not going back, and we don't really need the old method anymore, but if you want to attract non-JETTO IMAS use cases for duqtools, most of those are probably still using the `~/public/imasdb` folder paradigm for awhile yet.

Good to know. At the moment we do not have any use cases outside of Jetto. But any non-jetto imas cases will require their own interface anyway, so it is good that we make this behaviour part of the `System` system.
