### ISSUE TITLE
Make `.llcmd` compatible with jintrac version

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#488]
The .llcmd generated by duqtools is incorrect if the system does not match what is in `jetto.jset`.

For `v220922` it should be something like:

```
#!/bin/sh
#SBATCH -J jetto.run12345
#SBATCH -i /dev/null
#SBATCH -o ll.out
#SBATCH -e ll.err
#SBATCH -p gw

#SBATCH -t 48:0:00
#SBATCH --mem=20G

cd /pfs/work/g2ssmee/jetto/runs/test12345
/pfs/work/g2ssmee/jetto/runs/test12345/rjettov -S -I -p -xmpi -x64 test12345 v220922 g2fjc
```

Related to #484

**Comment by fcasson** [comment]
For batch script generation, we should maybe try to share a common tool?  We already have a python tool for generatrion of batch scripts across platforms (https://gitlab.eufus.psnc.pl/jintrac-mirror/jintrac/-/blob/develop/python/batchscript.py), I am sure if can be improved,  I guess you would need it moved into jetto-pythontools to be useful for both of us - or can use you use this one which sits in the jintrac repo?

**Comment by stefsmeets** [comment]
Writing the batch script is not really an issue. It's more that we should which parameters for jetto we should write (i.e. the `v220922 g2fjc` part). We grab this from `jetto.jset`, but it may or may not match the current environment.

**Comment by fcasson** [comment]
I think taking it from jetto.jset is the right approach.  We try not to make runtime behaviour dependent on env, and the jset is suppose to capture all the relvant infromation to use at runtime, including the version to use

**Comment by stefsmeets** [comment]
I looked into this today and I think this should be updated on the template via JAMS or otherwise. I don't think it makes much sense for us to hardcode this somewhere.
