### ISSUE TITLE
`duqduq setup` should overwrite values in template from IDS data

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#492]
Values to overwrite:

- `t_start`: take from `core_profiles/time[0]` (any IDS really)
- `t_end`: defined by `t_start` + some duration defined in config
- `major_radius`: take from `core_profiles/vacuum_toroidal_field/r0` (units: m)
- `Bfield`: take from `core_profiles/vacuum_toroidal_field/b0`

The input data does not specify `t_end`, so could we grab the time window from `jetto.jset` and make sure to modify `t_end` so that the duration matches the template?

**Comment by aaronkho** [comment]
Perhaps a `time_duration` field in the yaml can be used to set `t_end - t_start` and then you take `t_start` from the IDS?

**Comment by stefsmeets** [comment]
> Perhaps a `time_duration` field in the yaml can be used to set `t_end - t_start` and then you take `t_start` from the IDS?

I think this is a better approach (much simpler too).

**Comment by stefsmeets** [comment]
@aaronkho what would be the best place to grab the *major_radius* and *b_field* from in the IDS structure?

In your data set, some data sets define major radius as `-9e+40` and b_field is not defined at all.

Currently I'm usin these IDS:
- `b_field`: `core_profiles/vacuum_toroidal_field/b0`
- `major_radius`: `core_profiles/vacuum_toroidal_field/r0`

These are the data sets causing issues:
```
run_2,g2aho,jet,75225,0002
run_3,g2aho,jet,90350,0002
run_4,g2aho,jet,92432,0002
run_5,g2aho,jet,94875,0001
run_6,g2aho,tcv,64958,0002
```

The others data sets have the values defined in the IDS, so it's straightforward to grab them.

**Comment by aaronkho** [comment]
There are other fields where this data can be found:
- `b_field`: `equilibrium/vacuum_toroidal_field/b0` or `equilibrium/time_slice/0/global_quantities/magnetic_axis/b_field_tor`
- `major_radius`: `equilibrium/vacuum_torodial_field/r0` or `equilibrium/time_slice/0/global_quantities/magnetic_axis/r`

Note that the `IDSPULSESCHEDIN_BT` option grabs the data from `pulse_schedule/tf/b_field_tor_vacuum_r/reference/data` which represents `b_field * major_radius`.
