### ISSUE TITLE
pre-commit ruff hook does not work with nixos

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#496]
For me the hook always fails with:

```
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

[Errno 2] No such file or directory: '/home/vikko/.cache/pre-commit/repod0c9w_hr/py_env-python3.10/bin/ruff'
```

**Comment by v1kko** [comment]
I think it has something to do with ruff being some pre-compiled binary and therefore it cannot find some dependencies

**Comment by v1kko** [comment]
Fixed it by installing it with `pip install --no-binary ruff`

**Comment by v1kko** [comment]
For future me (or someone else using nixos) I have a working wheel of ruff for fast installation locally

**Comment by stefsmeets** [comment]
Seems like this can be closed, since it's a nix issue: https://github.com/NixOS/nixpkgs/issues/142383
