### ISSUE TITLE
Make the `create` step runnable in a docker container if imas+jintrac is not installed locally

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#506]

**Comment by v1kko** [comment]
This is actually much harder than I thought, I cannot think of a good way to transparently do this, so here are some thoughts:
- We cannot know how each container behaves, so `running inside` is not trivial and subject to changes in the required setup for example
- I know dask can export programs and run them on other computers transparently, however, it requires that the environments are "identical" which is definitely not the case here
- How, if we cannot use dask, do we call duqtools inside the container, do we mount it? or do we re-install via pip

So probably this is just a bad idea, or maybe I am missing something

**Comment by stefsmeets** [comment]
Have you considered setting up rpc server that wraps imas through a python script, and then starting the container via:

`docker-compose run imas /usr/bin/python /path/to/rpc_server.py`

And then calling into that server from duqtools and stream, read the data using imas, stream the data back to the host (numpy has good support for this), modify the data, stream the data back to the guest, and then write it using imas?

**Comment by v1kko** [comment]
> Have you considered setting up rpc server that wraps imas through a python script, and then starting the container via:
> 
> `docker-compose run imas /usr/bin/python /path/to/rpc_server.py`
> 
> And then calling into that server from duqtools and stream, read the data using imas, stream the data back to the host (numpy has good support for this), modify the data, stream the data back to the guest, and then write it using imas?

Might work, but we link into `imas` in a lot of places, so this could become very complex very quickly, let's hope `imas` becomes open source before we need to do this

**Comment by v1kko** [comment]
Might be useful, i think it does limit you to duqtools versions that are released on pypi, but other than that, it should work

**Comment by stefsmeets** [comment]
Hi @v1kko, is this still something you are planning to pursue? And is it feasible or can this issue be closed?

**Comment by v1kko** [comment]
Let's close it and focus more on open sourcing jintrac and imas so this becomes a non-issue
