### ISSUE TITLE
duqduq jobs have the wrong name in `.llcmd`

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#517]
The `.llcmd` files are written with the wrong run name in the job title. It always picks the last data entry.

e.g. with 10 data items:

- `data_06/run_0020/.llcmd` : `#SBATCH -J duqtools.data_10.run_0020`
- `data_10/run_0015/.llcmd` : `#SBATCH -J duqtools.data_10.run_0015`

**Comment by v1kko** [comment]
This is a small manifestation of a big problem:
- We have treated  `cfg` as a immutable singleton, however, with duqduq, there are now multiple `cfg` so this does not hold anymore

**Comment by stefsmeets** [comment]
I think we have to pass the tag or config to `self.system.write_batchfile` in `CreateManager.create_run`. This will have the correct context for config.

**Comment by stefsmeets** [comment]
This seems to happen again in the latest version of `duqtools`. I will have a look where it got reintroduced.
