### ISSUE TITLE
Consider using pyright

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#545]
I have been reading lots of nice things about [pyright](https://github.com/microsoft/pyright). I would be curious to try to see how it works with our codebase. The advantage is that it is [much faster and apparently the error messages are better](https://github.com/microsoft/pyright/blob/main/docs/mypy-comparison.md).

```console
$ pip install pyright
$ pyright src --skipunannotated --level=error
No configuration file found.
pyproject.toml file found at /home/stef/python/duqtools.
Loading pyproject.toml file at /home/stef/python/duqtools/pyproject.toml
Pyproject file "/home/stef/python/duqtools/pyproject.toml" is missing "[tool.pyright]" section.
stubPath /home/stef/python/duqtools/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 64 source files
pyright 1.1.298
...
53 errors, 0 warnings, 0 informations
Completed in 12.974sec
```

On a related note, we get ~50 type errors when running pyright (~20 with mypy) on our entire code base. This might be a good opportunity to look into that.

**Comment by v1kko** [comment]
I dislike that it is written in javascript. It seems to me the (very) wrong tool for the job.

**Comment by stefsmeets** [comment]
Yep, I'm going to close this for now.
