### ISSUE TITLE
Consider renaming `--dry_run` to `--no`

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#554]
For CLI consistency I was thinking it may be a good idea to rename `--dry_run` to `--no`. This makes it clear that it will list the tasks, but not execute anything.

With the current implementation, `--dry_run` already acts as the opposite of `--yes`.

**Comment by v1kko** [comment]
I don't think we should do this, as  `dry_run` is not supposed to be the opposite `yes`, but rather it should do everything as normal, but don't change anything on the filesystem
