### ISSUE TITLE
`duqtools fitness` to perform a function for each run

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#581]

**Comment by stefsmeets** [comment]
Why do we need this?

**Comment by v1kko** [comment]
A convenience function for users that want to evaluate some function `f` over all runs

**Comment by stefsmeets** [comment]
Your implementation iterates over the runs, shouldn't we apply this over the imas data instead?

**Comment by v1kko** [comment]
Of course this is all dependent on how users would actually want to use this, which we do not know :smile:
