### ISSUE TITLE
`duqtools init` should generate a configuration which is directly usable

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#583]

**Comment by stefsmeets** [comment]
Yes, agree! We should take out the `copyto` part. And I think the submit/status stuff can also be left out.

I'm also adding a note to include the `tag: ...` key.

**Comment by v1kko** [comment]
And perhaps the default should be `prominence`/`docker` as those systems are easier available than `slurm`

**Comment by stefsmeets** [comment]
Would it be helpful to pass options, like `duqtools init prominence` or even `duqtools init --system jetto --submit docker` to select the appropriate settings? Or will that be a pain to maintain?

Perhaps we could re-use those snippets in the documentation.
