### ISSUE TITLE
Questions about rebase_on_time

### ISSUE THREAD

**Issue by Marinmepfl** [duqtools/duqtools#605]
I have a couple of questions regarding the 'rebase_on_time' function:

1 - How is the new rho_tor_norm chosen? In principle it can vary in time in the original dataset, but a fixed grid must be chosen to perform the interpolation in time. How is this handled?
2 - I now have a dataset with all the data needed to create an IDS. How do I then write that into the IDS? I cannot really use a loop on write_array_in_parts since I need an already created dataset of the same time length

**Comment by stefsmeets** [comment]
Hi @Marinmepfl 

1. When loading the imas data into an xarray (using `ImasHandle.get_variables`) we run the function `squash_placeholders`. This function ensures all `rho_tor_norm` are the same for each time step by interpolating `rho_tor_norm` for each time step to t=0. In this way, we can use `rho_tor_norm` as a dimension in xarray.

    So yes, in principle it can vary in the imas data, but from our understanding for `jetto` it is always the same which is why we added this step.

    More info on squashing variables: https://duqtools.readthedocs.io/en/latest/variables/#squashing-data

2. It's not clear to me either how you could write this back to an IDS. I think you have to create an IDS from scratch to do that. In duqtools we have any functions to create an IDS from scratch.

**Comment by Marinmepfl** [comment]
Hi! Thanks for the reply

1 - For some applications (specifically, my application...) taking the tho_tor_norm at t=0 might not be good. I implemented something to get the grid in a smart way (for example, getting all the values and then iteratively eliminating the closest ones), but I am not sure on how to integrate it to the tools

2 -  'we have any functions to create an IDS from scratch' : do you mean that you do not have it? If I rebase in time and then want to take the new rebased data as input to the ids I probably need it :/

**Comment by stefsmeets** [comment]
1. Which function are you using? Or can you share your code? 

    For `rebase_on_time` and `rebase_on_grid` you can pass the coordinates you want to use directly (i.e. `rebase_on_time(ds, new_coords=your_time_coordinates)` or `rebase_on_grid(ds, new_coords=your_grid_coordinates)`). Does that work for you?

2. Oops, my bad. I meant that we do not have any functions to do that, and I don't think this is something that we will add.
