### ISSUE TITLE
Getting back data from prominence

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#636]
We can finally submit to prominence, but we have no (easy) way to get back the result to further use in the visualization pipeline. It can be done manually with `prominence download <runid>` for each run, which is a bit tedious

- [ ] One option would be to make a `duqtools sync-prominence` command which replaces the run directories with those executed on prominence.

Suggestions welcome!

**Comment by stefsmeets** [comment]
Do we have all the information we need to make `duqtools sync-prominence` work without any additional configuration?

**Comment by v1kko** [comment]
To download data from prominence you need the `<jobid>` which we (can, not sure if we do) save in the lockfile. Then the run can be downloaded with `prominence download <jobid>`. So I think it could be implemented without additional configuration.
