### ISSUE TITLE
Support JINTRAC / HFPS v230723

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#650]
Release notes:
https://users.euro-fusion.org/pages/data-cmg/wiki/JINTRAC_ReleaseNotes.html#jintrac-jams-release-notes-v230723

Main changes affecting duqtools:
- HDF5 is set as the default, see also #76

**Comment by stefsmeets** [comment]
@aaronkho Could you provide us with hdf5 test files?

**Comment by v1kko** [comment]
Interestingly duqtools seems to convert hdf5 runs to mds format when copying. 
- [ ] Investigate why this is happening

**Comment by v1kko** [comment]
Closing this as we decided to offload this problems to imaspy eventually
