### ISSUE TITLE
Consider dropping yapf for ruff formatter

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#669]
Formatting is now built into ruff (https://astral.sh/blog/the-ruff-formatter) as part of [0.1.2](https://github.com/astral-sh/ruff/releases/tag/v0.1.2).

It's about 100x faster than yapf. Although it is in preview, it's considered production ready.

**Comment by v1kko** [comment]
The ruff formatter is based on the [black formatter](https://github.com/psf/black). The difference with `yapf` is staggering:
```
62 files changed, 1233 insertions(+), 1107 deletions(-)
```

Black (and hence ruff) does not really provide any configuration [options](https://docs.astral.sh/ruff/settings/#format) so this diff doesn't get much better.

Therefore I suggest that we stick with `yapf` for this project, but for new projects the ruff formatter can be used
