### ISSUE TITLE
Modifying array values in Jetto namelist

### ISSUE THREAD

**Issue by aaronkho** [duqtools/duqtools#679]
The only examples / options for the JETTO lookup use `dimension: "scalar"`. Is there a way to allow it to modify array entries, even if it is just one variable per element?

**Comment by v1kko** [comment]
@aaronkho, after our last mail contact, Is this issue now solved?

**Comment by aaronkho** [comment]
There remains an additional problem. Some of the array variables that we want to modify are inside a separate structure in the underlying JSET model used by duqtools. They can be accessed using `jset_obj.extras[<var_name>]`. Is it possible to open up these fields to modification via duqtools through the JETTO lookup structure?

**Comment by v1kko** [comment]
Hi @aaronkho,

Does this relate to extra namelists (see  https://gitlab.com/jintrac/jetto-pythontools/-/blob/master/jetto_tools/config.py?ref_type=heads#L684 ) If that is the case then these can be supported with a small change in duqtools.

If this is something else then please let me know.

**Comment by aaronkho** [comment]
Yes, some of the targeted settings for this issue are in the extra namelists. However, these values also are themselves arrays (aka vectors in jetto-pythontools). I am unsure if the current duqtools yaml interface can handle changing values which are not scalar. Can you verify if this is possible?

In addition, I am also making some changes to jetto-pythontools itself to open up some arrays which are not in the extra namelists to the lookup table based modification. Although they are important to my study, they still need to be merged into the main branch. These will likely also need to array modification capability inside duqtools itself.

**Comment by aaronkho** [comment]
In case of the extra namelist items, this seems to already be adjustable by making sure `jest_id = null` in the lookup.json within the latest version of jetto-pythontools. Thus, the only thing that needs to be verified is whether `values` in the yaml can be set to lists, or a list of lists in the case of a scan.
