### ISSUE TITLE
Possible Packages mismatch on the gateway

### ISSUE THREAD

**Issue by Marinmepfl** [duqtools/duqtools#720]
I am trying to use the duqtools on the gateway, I have version 3.1.0.
I am trying to do a simple `from duqtools.api import ImasHandle` but I get the error 
`ImportError: cannot import name 'deprecated' from 'typing_extensions'`
I tried to upgrade `typing_extensions` with pip but it does not seem to solve the problem.

Am I making some mistake or there is some mismatch with the packages on the gateway?

**Comment by stefsmeets** [comment]
Actually, `from duqtools.api import ImasHandle` seems fine with fresh install.

What version of python and typing-extensions do you have? I'm on Python 3.10.2 with `typing_extensions==4.1.1`.

Can you post the full stack trace of your `ImportError`?

**Comment by Marinmepfl** [comment]
There seems to be some conflict with xarray and jetto_tools, if I remove the respective imports the script works again.
However, I now get 
`ImportError: cannot import name 'Variable' from 'duqtools.api' (/afs/eufus.eu/user/g/g2mmarin/.local/lib/python3.10/site-packages/duqtools/api.py)`

Is 'Variable' not a module anymore? I tested this on an older version of the duqtools.
What is the new module?

**Comment by stefsmeets** [comment]
Glad that you got it sorted. Gateway remains a bit of a minefield with dependency, because we are not in control of the full system.

Yeah, we moved `Varlable` to `imas2xarray`: https://imas2xarray.readthedocs.io/en/latest/api/#imas2xarray.Variable

**Comment by stefsmeets** [comment]
Just a thought that order of imports may matter here, for example importing duqtools first and _then_ xarray/jetto-tools. Duqtools has some work-arounds to make sure it loads the right version of a library: https://github.com/duqtools/duqtools/blob/main/src/duqtools/__init__.py

**Comment by Marinmepfl** [comment]
Thanks! Indeed changing the order of imports works :D

And I can now import 'Variable' again
