### ISSUE TITLE
Use of handle.get_variables

### ISSUE THREAD

**Issue by Marinmepfl** [duqtools/duqtools#721]
I have a piece of code that fails with the newest version of the code. 

I am using `single_dataset = handle.get_variables([variable])`, where variable is a single Variable (turned to a list since the function only accepts a list).

The error I get is 
```
File "/afs/eufus.eu/user/g/g2mmarin/.local/lib/python3.10/site-packages/duqtools/ids/__handle.py", line 239, in get_variables
    ids = var_models[0].ids
TypeError: 'set' object is not subscriptable
```

The script I am debugging is `/afs/eufus.eu/user/g/g2mmarin/public/scripts/setup_nbi_input.py`
and I am using it as 
python setup_nbi_input.py --ids 'g2mmarin/tcv/73388/2' --run_target 11 --path_run runbug_ascot_setup

**Comment by stefsmeets** [comment]
Does this work:

`ids = list(var_models)[0].ids`?

**Comment by Marinmepfl** [comment]
Yes, I substituted that line in `/afs/eufus.eu/user/g/g2mmarin/.local/lib/python3.10/site-packages/duqtools/ids/__handle.py `and everything works again
