### ISSUE TITLE
Allow incomplete runs to be plotted

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#98]
Plot the last known timestep and issue a warning in the case of incomplete data

**Comment by stefsmeets** [comment]
The way I have it now is that you can search the `IDSMapping` for keys using `.find_by_index`. This returns a list of numpy arrays that can be used for plotting more easily.

```python
ids = profile.get_ids_tree('core_profiles')
timesteps = ids.find_by_index(r'^profiles_1d/(\d+)/t_i_average$')
```

To get the last timestep we can use `timesteps[-1]`, and plot that.
